version: '3'
services:
  app1:
    build: ./app1
    ports:
    #escucha en el 5001 del Host Docker (172.17.0.1)
    - "5001:5000"
  app2:
    build: ./app2
    ports:
    #escucha en el 5002 del Host Docker (172.17.0.1)
    - "5002:5000"
  nginx:
    build: ./nginx 
    ports:
    #escucha en el 8080 del Host Docker (172.17.0.1)
    - "8080:80"
    depends_on:
      - app1
      - app2
